version: "3.8"
services:
  hpltransfers:
    build:
      context: .
    # image: public.ecr.aws/j5z8d4p7/hpltransfers:latest
    restart: always
    environment:
      - PORT=7000
      - LEDGER_PRINCIPAL=rqx66-eyaaa-aaaap-aaona-cai
      - DFX_NETWORK=ic
      - PRINCIPAL1_SECRET_KEY=Wallet123HPlScripts
      - PRINCIPAL2_SECRET_KEY=Wallet123HPlScripts2
      - INTERVAL_TIME=*/5 * * * * *
      - EXTRA_AGGREGATORS=tdjwp-lyaaa-aaaam-ab4uq-cai|dwqfg-iiaaa-aaaal-adnva-cai|masfb-qqaaa-aaaal-qdbrq-cai|zvyvp-4qaaa-aaaak-qc2za-cai|jjdh5-2yaaa-aaaaj-qa3lq-cai
    volumes: 
      - ./logs:/home/bun/app/logs
    ports:
      - 7000:7000