version: "3.8"
services:
  hpltransfers:
    image: public.ecr.aws/j5z8d4p7/hpltransfers:latest
    restart: always
    environment:
      - PORT=9000
      - LEDGER_PRINCIPAL=rqx66-eyaaa-aaaap-aaona-cai
      - DFX_NETWORK=ic
      - PRINCIPAL1_SECRET_KEY=Wallet123HPlScripts
      - PRINCIPAL2_SECRET_KEY=Wallet123HPlScripts2
      - INTERVAL_TIME=*/5 * * * * *
    ports:
      - 9000:9000